### ISSUE TITLE
Default Metric List includes non-existent metric - please tag new release

### ISSUE THREAD

**Issue by kyle-robbertze-ada** [SumoLogic/sumologic-mongodb-atlas#22]
When running the collector from pip, it now fails because Mongo has removed this metric:

```
Traceback (most recent call last):
  File "/layers/google.python.pip/pip/lib/python3.11/site-packages/sumoappclient/sumoclient/httputils.py", line 37, in make_request
    resp.raise_for_status()
  File "/layers/google.python.pip/pip/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: {"detail":"An invalid metric name DISK_PARTITION_UTILIZATION was specified.","error":404,"errorCode":"INVALID_METRIC_NAME","parameters":["DISK_PARTITION_UTILIZATION"],"reason":"Not Found"} for url: https://<MONGO_URL>/disks/data/measurements?itemsPerPage=500&granularity=PT1M&start=2024-07-10T08%3A45%3A00.001000Z&end=2024-07-10T08%3A46%3A08.000000Z&m=DISK_PARTITION_IOPS_READ&m=DISK_PARTITION_IOPS_WRITE&m=DISK_PARTITION_UTILIZATION&m=DISK_PARTITION_LATENCY_READ&m=DISK_PARTITION_LATENCY_WRITE&m=DISK_PARTITION_SPACE_PERCENT_FREE&m=DISK_PARTITION_SPACE_PERCENT_USED
```

This is has been fixed in fdffe52b606a7adc37fcfdb1b5e1f6885f58d4b3, but this fix has not been released on pypi. Please can you tag a new release with this fix?

**Comment by himanshu219** [comment]
This is fixed now https://github.com/SumoLogic/sumologic-mongodb-atlas/releases/tag/v2.0.1
